### ISSUE TITLE
ZED2I changed topics

### ISSUE THREAD

**Issue by tutunarsl** [leggedrobotics/grand_tour_box#1102]
All the newly generated zed2i bags have the updated topic name. As an example, we currently have this in  `grand_tour_box/box_calibration/box_calibration/calibration/zed2i/zed_right.yaml`

```
#Calibration program comments:2024-11-05-20-54-25
camera_matrix:
  cols: 3
  data: [1064.945423674698, 0.0, 954.6233348317302, 0.0, 1065.394939275629, 549.646146987725,
    0.0, 0.0, 1.0]
  rows: 3
distortion_coefficients:
  cols: 4
  data: [-0.05652460911455223, 0.0199628282728224, -0.0008376485354362096, -0.0001827638688556736]
  rows: 1
distortion_model: radtan
image_height: 1280
image_width: 1920
projection_matrix:
  cols: 4
  data: [1064.945423674698, 0.0, 954.6233348317302, 0.0, 0.0, 1065.394939275629, 549.646146987725,
    0.0, 0.0, 0.0, 1.0, 0.0]
  rows: 3
rectification_matrix:
  cols: 3
  data: [1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0]
  rows: 3
rostopic: /gt_box/zed2i_driver_node/right_raw/image_raw_color

```

Do we need to change this? As a reference this is a snapshot from an up to date zed2i iamge bag

```
topics:       /boxi/zed2i/left/camera_info             5441 msgs    : sensor_msgs/CameraInfo     
              /boxi/zed2i/left/image_raw/compressed    5441 msgs    : sensor_msgs/CompressedImage
              /boxi/zed2i/right/camera_info            5441 msgs    : sensor_msgs/CameraInfo     
              /boxi/zed2i/right/image_raw/compressed   5441 msgs    : sensor_msgs/CompressedImag
```
