### ISSUE TITLE
Refactor the box_health

### ISSUE THREAD

**Issue by JonasFrey96** [leggedrobotics/grand_tour_box#312]
Currently the package is not configurable via a YAML file.   
Make it easy to configure which topics one should listen to.   
The specific messages for each PC seem to be quite a bad idea given that the topics we would like to publish in each PC continuously will change.   

Started fixing things here:
https://github.com/leggedrobotics/grand_tour_box/tree/dev/rework_health_status

The message definition could be more general to have a single message definition using flexible size datafields to store everything. 
Further TODO:

- [ ] Create a list of things we should be monitoring
- [ ] Create a list of things that are dependent on the monitoring (e.g. how is the visualization done in RVIZ)
- [ ] What is the best output (single message) - a lot of individual messages
- [ ] What is the exact usecase and benefit
- [ ] Re-implement in a a more flexible way 

Example config file could look as follows:
```
jetson:
  topics:
    /gt_box/alphasense_driver_node/cam0:
      - min_rate: 9.5
      - max_rate: 11.0
      ...
  ptp_services:
    - phc2sys_mgbe0.service
    - phc2sys_mgbe1.service
    - ptp4l_mgbe0.service
    - ptp4l_mgbe1.service
  ntp_services:
    - TBD
```

Monitoring Ideas:
- PTP
- Chrony
- Topic Frequencies (was there a hick up)
- System Delay - Message received vs message timestamp
- Node Status (can we use output of fkie multimaster or so)
- (Disk Space)

What to publish and log:
