### ISSUE TITLE
Box Auto - Running on other machine. 

### ISSUE THREAD

**Issue by JonasFrey96** [leggedrobotics/grand_tour_box#524]
@fulkast @tutunarsl could you please try out the boxauto. 

## Requirements: 
nvidia_container_runtime installed
expects cuda 12.4 currently but you can also try with other cuda version

## Preperation
To change CUDA version:
- Modify: `~/git/grand_tour_box/box_utils/box_auto/docker/box.Dockerfile` top line. 

## Running box_auto
```shell
# Prepare the mission data directory
sudo mkdir /mission_data
chown -r username:username /mission_data

# Link some raw mission data
ln -s /some_rosbag_data /mission_data

cd ~git/grand_tour_box/box_utils/box_auto/docker
docker compose build
docker compose up
```

## How it works
Single container / dockerfile used for all runs and includes all box dependencies: 
```shell
~/git/grand_tour_box/box_utils/box_auto/docker/box.Dockerfile
```

The actual "work" happens mostly in python-scripts, that either call launch files or execute some python code and are located here:
```shell
~/git/grand_tour_box/box_utils/box_auto/scripts
```

The structure of the typical python script is:
```
1. get bags for input from /mission_data using e.g. rglob 
2. doing some processing
3. writing output to the same folder /mission_data
``` 

Docker compose file defines list of postprocessing tasks - The <<: *common-config defines the container params 

We can extend to multiple containers if needed. 

```yaml
services:
  mcap_to_rosbag:
    <<: *common-config
    container_name: mcap_to_rosbag
    command: ["python3", "/home/catkin_ws/src/grand_tour_box/box_utils/box_auto/scripts/mcap_to_rosbag.py"]

  zed2i:
    <<: *common-config
    container_name: zed2i
    command: ["python3", "/home/catkin_ws/src/grand_tour_box/box_utils/box_auto/scripts/zed2i.py"]

  repair_bags:
    <<: *common-config
    container_name: repair_bags
    command: ["python3", "/home/catkin_ws/src/grand_tour_box/box_utils/box_auto/scripts/repair_bags.py"]

  #STOP 0

  merge_mission:
    <<: *common-config
    container_name: merge_mission
    command: ["python3", "/home/catkin_ws/src/grand_tour_box/box_utils/box_auto/scripts/merge_mission.py"]
    depends_on:
      mcap_to_rosbag:
        condition: service_completed_successfully
      zed2i:
        condition: service_completed_successfully
      repair_bags:
        condition: service_completed_successfully
```
