### ISSUE TITLE
robot recording analysis

### ISSUE THREAD

**Issue by JonasFrey96** [leggedrobotics/grand_tour_box#574]
Looks generally pretty good.

```yaml
lpc:
  grpc_cfg:
    address: 192.168.0.141
    port: 50051
  bags:
    locomotion:
      - /debug_info
    general:

/anymal_low_level_controller/actuator_readings                  
/anymal_low_level_controller/actuator_readings_extended_throttled           
/foot_scan                                                                
/joy_manager/twist                                                        
/pdb/battery_state                                                        
/pdb/intrinsic_state                                                            
/pdb/power_state                                                               
/twist_mux/selected_input                                                             
/twist_mux/twist 

      - /motion_reference/command_pose # MISSING 
      - /motion_reference/command_twist # MISSING 
      - /sensors/battery_voltage # MISSING
      - /soft_emcy_stop # MISSING
      - /rsl_joystick_driver/twist  # MISSING
      - /rsl_joystick_module/twist  # MISSING
      - /joy_manager/twist # MISSING

    anymal_imu: # WORKING
      - /sensors/imu 

    state_estimator: # WORKING
      - /state_estimator/anymal_state
      - /state_estimator/odometry
      - /state_estimator/pose_in_odom
      - /state_estimator/twist_throttle
    depth_cameras: # WORKING
      - /depth_camera_front_upper/depth/camera_info
      - /depth_camera_front_upper/depth/image_rect_raw
      - /depth_camera_rear_upper/depth/camera_info
      - /depth_camera_rear_upper/depth/image_rect_raw
    tf: # WORKING
      - /tf
      - /tf_static
    clock_lpc: 
      - /clock # MISSING
npc:
  grpc_cfg:
    address: 192.168.0.142
    port: 50052
  bags:
    general:
      - /behavior_engine/status # WORKING
      - /chrony_monitor_npc/status   # MISSING
      - /cpu_monitor_npc/status   # MISSING
      - /cpu_loupe_npc/cpu_loupe   # MISSING
      - /disk_monitor_npc/status   # MISSING
      - /memory_monitor_npc/status   # MISSING
      - /network_monitor_npc/status   # MISSING
      - /pinger_npc_to_lpc/ping   # MISSING
    depth_cameras:  # WORKING
      - /depth_camera_left/depth/camera_info
      - /depth_camera_left/depth/image_rect_raw
      - /depth_camera_right/depth/camera_info
      - /depth_camera_right/depth/image_rect_raw
    velodyne: # DID NOT WORK (not not forget to enable LIDAR)
      - /lidar/packets
      - /lidar/point_cloud
      - /lidar/time_sync_status
      - /point_cloud_filter/lidar/point_cloud_filtered
    elevation_mapping: # WORKED
      - /elevation_mapping/elevation_map_raw

    # wide_angle_cameras:
    #   - /wide_angle_camera_front/image_color/compressed
    #   - /wide_angle_camera_front/camera_info
    #   - /wide_angle_camera_rear/image_color/compressed
    #   - /wide_angle_camera_rear/camera_info
```
